services:
#  my-web-server:
#    container_name: webserver
#    image: nginx
#    ports:
#      - 80:80
  my-cache-server:
    image: redis
    ports:
      - 6379:6379
  my-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pwd1234
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
